#!/usr/bin/env node
/**
 * M45：Prompt 管理现代化 — 从 prompts/*.md 生成 src/generated/PromptFragments.ts
 * 供 WorkflowPrompts / PromptVersionManager / Rule20 verify 共用同一文本源。
 */
import * as crypto from 'node:crypto';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const PROMPTS_DIR = path.join(ROOT, 'prompts');
const MANIFEST_PATH = path.join(PROMPTS_DIR, 'manifest.json');
const OUT_DIR = path.join(ROOT, 'src', 'generated');
const OUT_FILE = path.join(OUT_DIR, 'PromptFragments.ts');
const HASH_FILE = path.join(OUT_DIR, 'prompt-fragments.sha256');

function readManifest() {
  const raw = fs.readFileSync(MANIFEST_PATH, 'utf8');
  return JSON.parse(raw);
}

function readPromptFile(relPath) {
  const abs = path.join(PROMPTS_DIR, relPath);
  if (!fs.existsSync(abs)) {
    throw new Error(`prompt file missing: ${relPath}`);
  }
  return fs.readFileSync(abs, 'utf8').replace(/\r\n/g, '\n');
}

/** 解析 .md 内 ${EXPORT_NAME} 引用（用于 task-type 组合块）。 */
function resolveIncludes(content, byExport, stack = new Set()) {
  return content.replace(/\$\{([A-Z0-9_]+)\}/g, (_, name) => {
    const raw = byExport.get(name);
    if (!raw) {
      return `\${${name}}`;
    }
    if (stack.has(name)) {
      throw new Error(`prompt include cycle: ${name}`);
    }
    stack.add(name);
    const resolved = resolveIncludes(raw, byExport, stack);
    stack.delete(name);
    return resolved;
  });
}

function escapeTemplateLiteral(text) {
  return text.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
}

function sha256(text) {
  return crypto.createHash('sha256').update(text, 'utf8').digest('hex');
}

function build() {
  const manifest = readManifest();
  const fragments = manifest.fragments ?? [];
  const rawByExport = new Map();
  for (const frag of fragments) {
    rawByExport.set(frag.export, readPromptFile(frag.file));
  }
  const lines = [
    '/**',
    ' * AUTO-GENERATED by scripts/build-prompts.mjs — DO NOT EDIT.',
    ' * Edit prompts/*.md and prompts/manifest.json, then npm run build:prompts.',
    ' */',
    '',
  ];

  const slotEntries = [];
  const hashParts = [];

  for (const frag of fragments) {
    const raw = rawByExport.get(frag.export) ?? '';
    const content = resolveIncludes(raw, rawByExport);
    const exportName = frag.export;
    lines.push(`export const ${exportName} = \`${escapeTemplateLiteral(content)}\`;`);
    lines.push('');
    hashParts.push(`${exportName}:${sha256(content)}`);
    if (frag.slot) {
      slotEntries.push({
        slot: frag.slot,
        export: exportName,
        protected: !!frag.protected,
      });
    }
  }

  lines.push('/** PromptVersionManager 槽位 seed（内容与 export 常量同步）。 */');
  lines.push('export function getPromptFragmentSlotSeeds(): Record<string, { content: string; protected: boolean }> {');
  lines.push('  return {');
  for (const entry of slotEntries) {
    lines.push(
      `    ${entry.slot}: { content: ${entry.export}, protected: ${entry.protected} },`,
    );
  }
  lines.push('  };');
  lines.push('}');
  lines.push('');
  lines.push('export const PROMPT_FRAGMENT_EXPORTS = [');
  for (const frag of fragments) {
    lines.push(`  '${frag.export}',`);
  }
  lines.push('] as const;');
  lines.push('');

  fs.mkdirSync(OUT_DIR, { recursive: true });
  const out = lines.join('\n');
  fs.writeFileSync(OUT_FILE, out, 'utf8');
  fs.writeFileSync(HASH_FILE, `${hashParts.join('\n')}\n`, 'utf8');
  console.log(`[build-prompts] wrote ${path.relative(ROOT, OUT_FILE)} (${fragments.length} fragments)`);
}

build();
