/** Python 标准库顶层模块名（verify_imports 白名单中的 stdlib 子集）。 */
export const PYTHON_STDLIB_ROOTS = new Set([
  '__future__',
  'abc',
  'argparse',
  'asyncio',
  'collections',
  'concurrent',
  'contextlib',
  'copy',
  'csv',
  'dataclasses',
  'datetime',
  'decimal',
  'enum',
  'functools',
  'glob',
  'hashlib',
  'importlib',
  'inspect',
  'io',
  'itertools',
  'json',
  'logging',
  'math',
  'os',
  'pathlib',
  'pickle',
  'queue',
  'random',
  're',
  'shutil',
  'signal',
  'socket',
  'sqlite3',
  'string',
  'struct',
  'subprocess',
  'sys',
  'tempfile',
  'threading',
  'time',
  'traceback',
  'types',
  'typing',
  'unittest',
  'urllib',
  'uuid',
  'warnings',
  'weakref',
]);

export function isPythonStdlibRoot(name: string): boolean {
  return PYTHON_STDLIB_ROOTS.has(name.split('.')[0]!.toLowerCase());
}
