/** 输入上下文预算竞争时的类别优先级（数值越大越优先保留配额）。 */
export const INPUT_BUDGET_PRIORITY_DECISION_RECORD = 50;
export const INPUT_BUDGET_PRIORITY_GLOBAL_DECISION = 40;
export const INPUT_BUDGET_PRIORITY_USER_INPUT = 30;
export const INPUT_BUDGET_PRIORITY_STAGE_OUTPUT = 20;
export const INPUT_BUDGET_PRIORITY_OTHER = 15;
export const INPUT_BUDGET_PRIORITY_CODEBASE_SNAPSHOT = 5;
