/**
 * Stagent 配置读取 — re-export shim；实现已拆分至 settings/readers/*。
 */
export {
  DEFAULT_CONFIDENCE_PAUSE_THRESHOLD,
  DEFAULT_MEMORY_MAX_EXPERIENCE_ENTRIES,
  DEFAULT_CODEBASE_CONTEXT_MAX_TOKENS,
  DEFAULT_DAG_MAX_PARALLELISM,
  DEFAULT_CONTRACT_NODE_PAUSE_THRESHOLD,
  resolveConfidencePauseThreshold,
  resolveMemoryMaxExperienceEntries,
  resolveCodebaseContextMaxTokens,
  resolveDagMaxParallelism,
  resolveContractNodePauseThreshold,
} from './StagentSettingsDefaults';

export {
  getStagentConfiguration,
  readContractNodePauseThreshold,
  readPauseContractNodesEnabled,
  readRedGreenGateMode,
  readDebugFeedbackLoopMode,
  readDebugFeedbackLoopRuntimeHard,
  readDebugRequireFeedbackLoop,
  readGrillAdaptiveModeEnabled,
  readCharterEnabled,
  readCharterAutoAnswerMode,
  readCharterRelativePath,
  readCharterFeedbackEnabled,
  readCharterFeedbackCooldownDays,
  readGlossaryEnabled,
  readArchitectureDepthScoringEnabled,
  readPlanCompletenessGateEnabled,
  readPlanStructuralRepairMode,
  readConfidencePauseThreshold,
  readMemoryExperienceStoreEnabled,
  readMemoryMaxExperienceEntries,
  readCodebaseContextEnabled,
  readCodebaseContextMaxTokens,
  readDagMaxParallelism,
  readSandboxEnabled,
  readSandboxVerificationOnly,
  readExperienceInjectOnGenerate,
  readPromptVersionsEnabled,
  readStaticAnalysisEnabled,
  readLlmTimeoutMs,
  readLlmMaxOutputTokens,
  readDebugVerbose,
  readAutoInsertGlobalArchitectureDecisionEnabled,
  readRuntimeRule20VerifyEnabled,
  readDecisionContentLintEnabled,
  readMaxManualStageRetries,
  readMaxWorkflowParseRetries,
  readInjectApprovedDecisionContext,
  readGlobalDecisionInjectMode,
  readHitlDecisionMode,
  readTestRunPreflightEnabled,
  readSplitTestRunBundledCommandsEnabled,
  readTestRunAutoNpmInstallEnabled,
  readWriteOutputIntegrityMode,
  readTestRunFailurePlaybookEnabled,
  readToIssuesHorizontalLayeringFail,
  readSdkPathContractLintMode,
  readPythonExportContractLintMode,
  readPythonPypiSymbolLintMode,
  readGateAutoRepairEnabled,
  readRuntimeReplanEnabled,
  readDangerousCommandLintMode,
  readContractInfraChainV2Enabled,
  readContractPlanPreflightV2Enabled,
  readContractCommitmentsEnabled,
  readContractCommitmentsLlmFallbackEnabled,
  readContractRuntimePreflightV2Enabled,
  readContractBoundExecutionEnabled,
  readContractDiagnosticRouterEnabled,
  readSettingsProfileId,
  type DebugFeedbackLoopMode,
  type PlanStructuralRepairMode,
  type SdkPathContractLintMode,
  type PythonExportContractLintMode,
  type PythonPypiSymbolLintMode,
  type DangerousCommandLintMode,
  type WriteOutputIntegrityMode,
} from './settings/SettingsReaders';

export {
  SETTINGS_DOMAIN_CATALOG,
  SETTINGS_PROFILES,
  formatSettingsValidationReport,
  getSettingsProfile,
  getSettingsProfileOverrides,
  validateSettings,
  type SettingsDomain,
  type SettingsProfileId,
  type SettingsProfileSpec,
  type SettingsValidationIssue,
  type SettingsValidationSeverity,
  type SettingDomainEntry,
} from './StagentSettingsGovernance';
