import {
  readArchitectureDepthScoringEnabled,
  readConfidencePauseThreshold,
  readContractNodePauseThreshold,
  readDebugFeedbackLoopRuntimeHard,
  readPauseContractNodesEnabled,
  readRedGreenGateMode,
  readSdkPathContractLintMode,
  readPythonExportContractLintMode,
  readPythonPypiSymbolLintMode,
  readStaticAnalysisEnabled,
  readTestRunFailurePlaybookEnabled,
  readTestRunPreflightEnabled,
  readTestRunAutoNpmInstallEnabled,
  readCharterAutoAnswerMode,
  readHitlDecisionMode,
} from '../StagentSettings';

export const qualityGateSettingsReaders = {
  readRedGreenGateMode,
  readDebugFeedbackLoopRuntimeHard,
  readTestRunPreflightEnabled,
  readTestRunAutoNpmInstallEnabled,
  readSdkPathContractLintMode,
  readPythonExportContractLintMode,
  readPythonPypiSymbolLintMode,
  readStaticAnalysisEnabled,
  readConfidencePauseThreshold,
  readContractNodePauseThreshold,
  readPauseContractNodesEnabled,
  readArchitectureDepthScoringEnabled,
  readTestRunFailurePlaybookEnabled,
  readCharterAutoAnswerMode,
  readHitlDecisionMode,
};
