import * as fs from 'fs';
import * as path from 'path';

export const CONFTEST_BASENAME = 'conftest.py';

/** flat layout：将 workspace 根加入 sys.path，使 tests/ 可 import 顶层模块。 */
export const CONFTEST_TEMPLATE = `import sys
from pathlib import Path

# Auto-generated by stagent: flat-layout pytest bootstrap
sys.path.insert(0, str(Path(__file__).resolve().parent))
`;

export function conftestAbsPath(cwd: string): string {
  return path.join(cwd, CONFTEST_BASENAME);
}

export function conftestExistsOnDisk(cwd: string): boolean {
  return fs.existsSync(conftestAbsPath(cwd));
}

/** 写盘 conftest.py（幂等：已存在则跳过）。返回是否新写入。 */
export function ensureConftestOnDisk(cwd: string): { written: boolean; path: string } {
  const abs = conftestAbsPath(cwd);
  if (fs.existsSync(abs)) {
    return { written: false, path: abs };
  }
  fs.writeFileSync(abs, CONFTEST_TEMPLATE, 'utf8');
  return { written: true, path: abs };
}
